import localFont from "next/font/local";
import "./globals.css";
import { Metadata } from 'next'


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
 //title: "Create Next App",
  //description: "Generated by create next app",
//themeColor: '#212529'
};



//


export default function RootLayout({ children }) {
  return (

 
 
    <html lang="en">
 
<head>
<title>DashBoard</title>
<meta name="theme-color" content="#781D76" />
</head>
 

      <body >
        {children}
      </body>
    </html>
  
  );
}
