import localFont from "next/font/local";
import "./globals.css";



const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
 //title: "Create Next App",
  //description: "Generated by create next app",

};



//


export default function RootLayout({ children }) {
  return (

 
 
    <html lang="en">
 
<head>
<title>DashBoard</title>
<meta name="theme-color" content="#540642" />
<meta name="description"
  content="Lalit Iots
  provides information about Open Web technologies
  including HTML, CSS, and APIs for both websites and
  progressive web apps." />



</head>
 

      <body >
        {children}
      </body>
    </html>
  
  );
}
